export const USER_ACTION_TYPES = {
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  EMAIL_SIGNIN_START: "EMAIL_SIGNIN_START",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAILED: "USER_SIGNIN_FAILED",
  USER_SIGN_UP_START: "USER_SIGN_UP_START",
  USER_SIGN_UP_SUCCESS: "USER_SIGN_UP_SUCCESS",
  USER_SIGN_UP_FAILED: "USER_SIGN_UP_FAILED",
  USER_SIGN_OUT_START: "USER_SIGN_OUT_START",
  USER_SIGN_OUT_SUCCESS: "USER_SIGN_OUT_SUCCESS",
  USER_SIGN_OUT_FAILED: "USER_SIGN_OUT_FAILED",
};
